DaisyForum.WebPortal/Models/ListByCategoryIdViewModel.cs
using DaisyForum.ViewModels;
using DaisyForum.ViewModels.Contents;

namespace DaisyForum.WebPortal.Models;

public class ListByCategoryIdViewModel
{
    public Pagination<KnowledgeBaseQuickViewModel>? Data { set; get; }
    public CategoryViewModel? Category { set; get; }
}

DaisyForum.WebPortal/Controllers/Components/PagerViewComponent.cs
using DaisyForum.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DaisyForum.WebPortal.Controllers.Components;

public class PagerViewComponent : ViewComponent
{
    public Task<IViewComponentResult> InvokeAsync(PaginationBase result)
    {
        return Task.FromResult((IViewComponentResult)View("Default", result));
    }
}

DaisyForum.WebPortal/Controllers/KnowledgeBaseController.cs
using DaisyForum.ViewModels.Contents;
using DaisyForum.WebPortal.Extensions;
using DaisyForum.WebPortal.Models;
using DaisyForum.WebPortal.Services;
using Microsoft.AspNetCore.Mvc;

namespace DaisyForum.WebPortal.Controllers
{
    public class KnowledgeBaseController : Controller
    {
        private readonly IKnowledgeBaseApiClient _knowledgeBaseApiClient;
        private readonly ICategoryApiClient _categoryApiClient;
        private readonly IConfiguration _configuration;
        private readonly ILabelApiClient _labelApiClient;
        private readonly IUserApiClient _userApiClient;

        public KnowledgeBaseController(IKnowledgeBaseApiClient knowledgeBaseApiClient,
            ICategoryApiClient categoryApiClient,
            ILabelApiClient labelApiClient,
            IUserApiClient userApiClient,
            IConfiguration configuration)
        {
            _knowledgeBaseApiClient = knowledgeBaseApiClient;
            _categoryApiClient = categoryApiClient;
            _configuration = configuration;
            _labelApiClient = labelApiClient;
            _userApiClient = userApiClient;
        }

        public async Task<IActionResult> ListByCategoryId(int id, int page = 1)
        {
            var pageSize = int.Parse(_configuration["PageSize"]);
            var category = await _categoryApiClient.GetCategoryById(id);
            var data = await _knowledgeBaseApiClient.GetKnowledgeBasesByCategoryId(id, page, pageSize);
            var viewModel = new ListByCategoryIdViewModel()
            {
                Data = data,
                Category = category
            };
            return View(viewModel);
        }

        public async Task<IActionResult> Search(string keyword, int page = 1)
        {
            var pageSize = int.Parse(_configuration["PageSize"]);
            var data = await _knowledgeBaseApiClient.SearchKnowledgeBase(keyword, page, pageSize);
            var viewModel = new SearchKnowledgeBaseViewModel()
            {
                Data = data,
                Keyword = keyword
            };
            return View(viewModel);
        }

        public async Task<IActionResult> ListByTag(string tagId, int page = 1)
        {
            var pageSize = int.Parse(_configuration["PageSize"]);
            var data = await _knowledgeBaseApiClient.GetKnowledgeBasesByTagId(tagId, page, pageSize);
            var label = await _labelApiClient.GetLabelById(tagId);
            var viewModel = new ListByTagIdViewModel()
            {
                Data = data,
                LabelVm = label
            };
            return View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var knowledgeBase = await _knowledgeBaseApiClient.GetKnowledgeBaseDetail(id);
            var category = await _categoryApiClient.GetCategoryById(knowledgeBase.CategoryId);
            var labels = await _knowledgeBaseApiClient.GetLabelsByKnowledgeBaseId(id);

            var viewModel = new KnowledgeBaseDetailViewModel()
            {
                Detail = knowledgeBase,
                Category = category,
                Labels = labels
            };
            if (User.Identity.IsAuthenticated)
            {
                viewModel.CurrentUser = await _userApiClient.GetById(User.GetUserId());
            }
            await _knowledgeBaseApiClient.UpdateViewCount(id);
            return View(viewModel);
        }

        #region AJAX Methods

        public async Task<IActionResult> GetCommentsByKnowledgeBaseId(int knowledgeBaseId, int pageIndex = 1, int pageSize = 2)
        {
            var data = await _knowledgeBaseApiClient.GetCommentsTree(knowledgeBaseId, pageIndex, pageSize);
            return Ok(data);
        }

        public async Task<IActionResult> GetRepliedCommentsByKnowledgeBaseId(int knowledgeBaseId, int rootCommentId, int pageIndex = 1, int pageSize = 2)
        {
            var data = await _knowledgeBaseApiClient.GetRepliedComments(knowledgeBaseId, rootCommentId, pageIndex, pageSize);
            return Ok(data);
        }

        [HttpPost]
        public async Task<IActionResult> AddNewComment([FromForm] CommentCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = await _knowledgeBaseApiClient.PostComment(request);
            if (result != null)
                return Ok(result);
            return BadRequest();
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteComment(int knowledgeBaseId, int commentId)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = await _knowledgeBaseApiClient.DeleteComment(knowledgeBaseId, commentId);
            if (result != null)
                return Ok(result);
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> PostVote([FromForm] VoteCreateRequest request)
        {
            var result = await _knowledgeBaseApiClient.PostVote(request);
            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> PostReport([FromForm] ReportCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _knowledgeBaseApiClient.PostReport(request);
            return Ok(result);
        }

        #endregion AJAX Methods
    }
}

DaisyForum.WebPortal/Views/KnowledgeBase/ListByCategoryId.cshtml
@model ListByCategoryIdViewModel
@{
    Layout = "_SubLayout";
    string suffixPage = Model.Data.PageIndex > 1 ? " - Trang " + Model.Data.PageIndex : "";
    ViewData["Title"] = Model.Category.Name + suffixPage;
    ViewData["Description"] = "Các bài viết trong danh mục " + Model.Category.SeoDescription + suffixPage;
}

<ul class="list-group list-group-flush">
    @if (Model.Data.Items != null)
    {
        foreach (var item in Model.Data.Items)
        {
            var url = "/bai-dang/" + item.SeoAlias + "-" + item.Id + "/";
            <li class="list-group-item">


                <label class="post-title h4">
                    <a class="text-decoration-none text-light-emphasis" href="@url">@item.Title</a>
                </label>

                <div class="d-flex">
                    <span class="d-block opacity-50 me-2">@item.CreateDate.ToString("dd/MM/yyyy")
                        trong
                    </span>
                    <span class="me-3"><a class="text-decoration-none" href="/danh-muc/@item.CategoryAlias-@item.CategoryId"
                            title="Xem tất cả bài viết trong @item.CategoryName">@item.CategoryName</a></span>

                    <a href="@url" style="width: fit-content"
                        class="me-2 badge d-flex align-items-center p-1 pe-2 text-primary bg-primary-subtle border border-primary-subtle rounded-pill text-decoration-none">
                        <i class="bi bi-chat-quote-fill me-1"></i>Bình luận
                        @item.NumberOfComments.GetValueOrDefault(0).ToString("N0")
                    </a>

                    <a href="@url" style="width: fit-content"
                        class="m-0 badge d-flex align-items-center p-1 pe-2 text-success bg-success-subtle border border-success-subtle rounded-pill text-decoration-none">
                        <i class="bi bi-hand-thumbs-up-fill me-1"></i>Thích
                        @item.NumberOfVotes.GetValueOrDefault(0).ToString("N0")
                    </a>
                </div>
                <p>
                    @Html.Raw(item.Description)
                </p>
            </li>
        }
    }
</ul>

DaisyForum.WebPortal/Views/KnowledgeBase/ListByTag.cshtml
@model ListByTagIdViewModel
@{
    Layout = "_SubLayout";
    string suffixPage = Model.Data.PageIndex > 1 ? " - Trang " + Model.Data.PageIndex : "";
    ViewData["Title"] = Model.LabelVm.Name + suffixPage;
    ViewData["Description"] = "Các bài viết liên quan đến thẻ " + Model.LabelVm.Name + suffixPage;
}

<style>
    .isolate {
        max-height: calc(1.2em * 5);
        /* Chiều cao tối đa của 5 dòng văn bản */
        overflow: hidden;
        /* Ẩn nội dung vượt quá chiều cao tối đa */
        text-overflow: ellipsis;
        /* Thêm dấu "..." vào cuối nội dung bị ẩn */
        display: -webkit-box;
        /* Sử dụng các thuộc tính tương thích với trình duyệt Safari */
        -webkit-line-clamp: 5;
        /* Giới hạn số dòng hiển thị là 5 */
        -webkit-box-orient: vertical;
        /* Hiển thị các dòng theo chiều dọc */
    }
</style>

<!-- start of page content -->
<ul class="list-group list-group-flush">
    @foreach (var item in Model.Data.Items)
    {
        var url = "/bai-dang/" + item.SeoAlias + "-" + item.Id + "/";
        <li class="list-group-item">


            <label class="post-title h4">
                <a class="text-decoration-none text-light-emphasis" href="@url">@item.Title</a>
            </label>

            <div class="d-flex">
                <span class="d-block opacity-50 me-2">@item.CreateDate.ToString("dd/MM/yyyy")
                    trong
                </span>
                <span class="me-3"><a class="text-decoration-none" href="/danh-muc/@item.CategoryAlias-@item.CategoryId"
                        title="Xem tất cả bài viết trong @item.CategoryName">@item.CategoryName</a></span>

                <a href="@url" style="width: fit-content"
                    class="me-2 badge d-flex align-items-center p-1 pe-2 text-primary bg-primary-subtle border border-primary-subtle rounded-pill text-decoration-none">
                    <i class="bi bi-chat-quote-fill me-1"></i>Bình luận
                    @item.NumberOfComments.GetValueOrDefault(0).ToString("N0")
                </a>

                <a href="@url" style="width: fit-content"
                    class="m-0 badge d-flex align-items-center p-1 pe-2 text-success bg-success-subtle border border-success-subtle rounded-pill text-decoration-none">
                    <i class="bi bi-hand-thumbs-up-fill me-1"></i>Thích
                    @item.NumberOfVotes.GetValueOrDefault(0).ToString("N0")
                </a>
            </div>
            <p>
                @Html.Raw(item.Description)
            </p>
        </li>
    }
</ul>
@(await Component.InvokeAsync("Pager", Model.Data))
<!-- end of page content -->

DaisyForum.WebPortal/Views/KnowledgeBase/Search.cshtml
@model SearchKnowledgeBaseViewModel
@{
    ViewData["Title"] = "Kết quả tìm kiếm cho từ khóa " + Model.Keyword;
    Layout = "~/Views/Shared/_SubLayout.cshtml";
    ViewData["Description"] = "Các bài viết được tìm bởi từ khóa " + Model.Keyword;
}
<!-- start of page content -->
<div class="list-group list-group-flush">
    @foreach (var item in Model.Data.Items)
    {
        var url = "/bai-dang/" + item.SeoAlias + "-" + item.Id + "/";
        <li class="list-group-item">


            <label class="post-title h4">
                <a class="text-decoration-none text-light-emphasis" href="@url">@item.Title</a>
            </label>

            <div class="d-flex">
                <span class="d-block opacity-50 me-2">@item.CreateDate.ToString("dd/MM/yyyy")
                    trong
                </span>
                <span class="me-3"><a class="text-decoration-none" href="/danh-muc/@item.CategoryAlias-@item.CategoryId"
                        title="Xem tất cả bài viết trong @item.CategoryName">@item.CategoryName</a></span>

                <a href="@url" style="width: fit-content"
                    class="me-2 badge d-flex align-items-center p-1 pe-2 text-primary bg-primary-subtle border border-primary-subtle rounded-pill text-decoration-none">
                    <i class="bi bi-chat-quote-fill me-1"></i>Bình luận
                    @item.NumberOfComments.GetValueOrDefault(0).ToString("N0")
                </a>

                <a href="@url" style="width: fit-content"
                    class="m-0 badge d-flex align-items-center p-1 pe-2 text-success bg-success-subtle border border-success-subtle rounded-pill text-decoration-none">
                    <i class="bi bi-hand-thumbs-up-fill me-1"></i>Thích
                    @item.NumberOfVotes.GetValueOrDefault(0).ToString("N0")
                </a>
            </div>
            <p>
                @Html.Raw(item.Description)
            </p>
        </li>
    }

    @(await Component.InvokeAsync("Pager", Model.Data))
</div>
<!-- end of page content -->