DaisyForum.WebPortal/Controllers/Components/FooterViewComponent.cs
using DaisyForum.WebPortal.Services;
using Microsoft.AspNetCore.Mvc;

namespace DaisyForum.WebPortal.Controllers.Components;

public class FooterViewComponent : ViewComponent
{
    private ICategoryApiClient _categoryApiClient;

    public FooterViewComponent(ICategoryApiClient categoryApiClient)
    {
        _categoryApiClient = categoryApiClient;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var categories = await _categoryApiClient.GetCategories();
        return View("Default", categories);
    }
}

DaisyForum.WebPortal/Controllers/Components/NavBarViewComponent.cs
using DaisyForum.ViewModels.Contents;
using DaisyForum.WebPortal.Services;
using Microsoft.AspNetCore.Mvc;

namespace DaisyForum.WebPortal.Controllers.Components;

public class NavBarViewComponent : ViewComponent
{
    private ICategoryApiClient _categoryApiClient;

    public NavBarViewComponent(ICategoryApiClient categoryApiClient)
    {
        _categoryApiClient = categoryApiClient;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var categories = await _categoryApiClient.GetCategories();
        var treeNodes = ConvertToTreeNodes(categories);

        return View("Default", treeNodes);
    }

    public class TreeNode
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int? ParentId { get; set; }
        public string? SeoAlias { get; set; }
        public List<TreeNode> Children { get; set; } = new List<TreeNode>();

        public TreeNode(int id, string? name, int? parentId, string? seoAlias, List<TreeNode> children)
        {
            Name = name;
            Id = id;
            ParentId = parentId;
            Children = children;
            SeoAlias = seoAlias;
        }
    }

    public static List<TreeNode> ConvertToTreeNodes(List<CategoryViewModel> categories, int? parentId = null)
    {
        var treeNodes = new List<TreeNode>();
        foreach (var category in categories.Where(c => c.ParentId == parentId))
        {
            var children = ConvertToTreeNodes(categories, category.Id);
            var treeNode = new TreeNode(category.Id, category.Name, category.ParentId, category.SeoAlias, children);
            treeNodes.Add(treeNode);
        }
        return treeNodes;
    }
}

DaisyForum.WebPortal/Controllers/Components/SideBarViewComponent.cs
using DaisyForum.ViewModels.Contents;
using DaisyForum.WebPortal.Models;
using DaisyForum.WebPortal.Services;
using Microsoft.AspNetCore.Mvc;

namespace DaisyForum.WebPortal.Controllers.Components;

public class SideBarViewComponent : ViewComponent
{
    private ICategoryApiClient _categoryApiClient;
    private IKnowledgeBaseApiClient _knowledgeBaseApiClient;

    public SideBarViewComponent(ICategoryApiClient categoryApiClient,
        IKnowledgeBaseApiClient knowledgeBaseApiClient)
    {
        _categoryApiClient = categoryApiClient;
        _knowledgeBaseApiClient = knowledgeBaseApiClient;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var categories = await _categoryApiClient.GetCategories();
        var treeNodes = TreeNode.ConvertToTreeNodes(categories);
        var popularKnowledgeBases = await _knowledgeBaseApiClient.GetPopularKnowledgeBases(5);
        var recentComments = await _knowledgeBaseApiClient.GetRecentComments(5);
        var viewModel = new SideBarViewModel()
        {
            TreeNodes = treeNodes,
            PopularKnowledgeBases = popularKnowledgeBases,
            RecentComments = recentComments
        };
        return View("Default", viewModel);
    }
}

DaisyForum.WebPortal/Views/Shared/_Layout.cshtml
@* @inject IConfiguration Configuration
@{
var siteKey = Configuration.GetSection("GoogleRecaptcha").GetSection("Sitekey").Value ?? "";
} *@
<!DOCTYPE html>
<html lang="vi-VN">

<head>
    <!-- META TAGS -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewData["Title"]</title>
    <meta name="description" content="@ViewData["Description"]">

    <link rel="shortcut icon" href="~/favicon.svg">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,500,600,400i,700&display=fallback">

    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    @* <script>
    window.OneSignal = window.OneSignal || [];
    OneSignal.push(function () {
    OneSignal.init({
    appId: "9dc7aa96-3d3a-473c-adf6-71bf429ce505",
    });
    });
    </script> *@
</head>

<body data-bs-theme="light">
    <!-- Start of Header -->
    <div>
        <!-- Start of Main Navigation -->
        @await Component.InvokeAsync("NavBar")
        <!-- End of Main Navigation -->
    </div>

    @* <partial name="_SearchBar" /> *@

    <div style="margin-top: 4.75rem">
        @RenderBody()
    </div>

    @await Component.InvokeAsync("Footer")
    <!-- End of Footer -->

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>
    <script type='text/javascript' src='/js/jquery-1.8.3.min.js'></script>
    <script type='text/javascript' src='/js/prettyphoto/jquery.prettyPhoto.js'></script>
    <script type='text/javascript' src='/js/jquery.liveSearch.js'></script>
    <script type='text/javascript' src='/js/jquery.form.js'></script>
    <script type='text/javascript' src='/js/jquery.validate.min.js'></script>
    <script type='text/javascript' src='/js/custom.js'></script>
    <script type="text/javascript" src="/js/site.js"></script>
    </script>
    <partial name="_ValidationScriptsPartial" />
    @RenderSection("scripts", required: false)
</body>

</html>

DaisyForum.WebPortal/Views/Shared/_SearchBar.cshtml
@* <header style="margin-top: 58px;" class="py-3 mb-4 border-bottom">
<div class="container d-flex flex-wrap justify-content-center">
<a class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none navbar-brand"
href="/" title="Daisy Forum">
<img height="38px" width="auto" src="/favicon.svg" alt="Daisy Forum logo">
Daisy Forum
</a>
<form id="search-form" method="get" action="/tim-kiem" autocomplete="off" class="w-50 col-lg-auto mb-3 mb-lg-0"
role="search">
<input type="search" class="form-control" name="keyword" placeholder="Bạn có câu hỏi?" aria-label="Search">
<div id="search-error-container"></div>
</form>
</div>
</header> *@

DaisyForum.WebPortal/Views/Shared/_SubLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    @RenderSection("scripts", required: false)
}
<div class="container">
    <div class="row">
        <div class="col-md-8">@RenderBody()</div>
        <div class="col-md-4">
            <!-- start of sidebar -->
            @await Component.InvokeAsync("SideBar")
            <!-- end of sidebar -->
        </div>
    </div>
</div>